services:
  - type: web
    name: clash-royale-store
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: UTMIFY_API_TOKEN
        sync: false
      - key: CR_API_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
